DROP TABLE IF EXISTS SEARCH_RESULT;

CREATE TABLE SEARCH_RESULT
(
    ID        INT           NOT NULL AUTO_INCREMENT,
    USER_IP   VARCHAR(15)   NOT NULL COMMENT '사용자 IP',
    KEYWORD   VARCHAR(5000) NOT NULL COMMENT '검색 키워드',
    SEARCH_DT DATETIME      NOT NULL COMMENT '검색 시간',
    PRIMARY KEY (ID)
) ENGINE = INNODB;